[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

; Velocità della porta seriale (indispensabile per lo streaming di dati pesanti)
monitor_speed = 115200
upload_speed = 921600

; Configurazione della memoria e partizionamento
board_build.partitions = huge_app.csv

; Build Flags per PSRAM e correzione bug cache
build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -mfix-esp32-psram-cache-strategy=memw

; Dipendenze: Carica la libreria ufficiale per il sensore OV2640
lib_deps =
    esp32-camera
    tanakamasayuki/TensorFlowLite_ESP32 @ 1.0.0